name: Docker Publish

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      RECALL2CACHE_VERSION: 2025.08.14
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Log in to the Container registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ./recall2cache
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/recall2cache:latest
            ghcr.io/${{ github.repository_owner }}/recall2cache:${{ env.RECALL2CACHE_VERSION }}
          build-args: |
            RECALL2CACHE_VERSION=${{ env.RECALL2CACHE_VERSION }}
